version: '3.9'
services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: backend
    env_file:
      - .env.template
    ports:
      - "8000:8000"
    volumes:
      - shared:/data/shared
    restart: unless-stopped
    depends_on:
      - qdrant

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: frontend
    env_file:
      - .env.template
    ports:
      - "8501:8501"
    volumes:
      - shared:/data/shared
    restart: unless-stopped
    depends_on:
      - backend

  qdrant:
    image: qdrant/qdrant:latest
    container_name: qdrant
    ports:
      - "6333:6333"
      - "6334:6334"
    volumes:
      - qdrant_storage:/qdrant/storage
    restart: unless-stopped

  n8n:
    image: n8nio/n8n:latest
    container_name: n8n
    ports:
      - "5678:5678"
    env_file:
      - .env.template
    volumes:
      - n8n_storage:/home/node/.n8n
      - shared:/data/shared
    restart: unless-stopped
    depends_on:
      - qdrant

volumes:
  qdrant_storage:
  n8n_storage:
  shared:
